default:
  site_name:
  welcome_message: "Welcome to Annotation Studio"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#CCC'
  brand: 'shared/default_brand'
  home_banner: 'cove_home_banner.jpg'
public:
  site_name: Public
  welcome_message: "Welcome to Annotation Studio"
  welcome_blurb: "Annotation Studio is a web application that supports close reading and collaborative interpretation of online documents. For more information on the project click the About link at the top. If you don’t have an account yet, click Register at the top of this page otherwise just log in."
  site_color: '#CCC'
  home_banner: 'cove_home_banner.jpg'
studio.covecollective.org:
  site_name: COVE
  oauth_provider: NAVSA
  welcome_message: 'Sign in above, or via <a href="http://navsa.org">NAVSA</a>'
  welcome_blurb: 'COVE Studio is the annotation and peer review workbench for COVE edition documents, which you can view on the <a href="http://dev-rc-distro.pantheonsite.io">COVE editions</a> website.'
  site_color: '#279eb2'
  home_banner: 'cove_home_banner.jpg'
  brand: 'shared/cove_brand'
staging.covecollective.org:
  site_name: COVE Staging
  oauth_provider: NAVSA
  welcome_message: 'Sign in above, or via <a href="http://navsa.org">NAVSA</a>'
  welcome_blurb: 'COVE Studio is the annotation and peer review workbench for COVE edition documents, which you can view on the <a href="http://dev-rc-distro.pantheonsite.io">COVE editions</a> website.'
  site_color: '#279eb2'
  home_banner: 'cove_home_banner.jpg'
  brand: 'shared/cove_brand'
navsaconference.covecollective.org:
  site_name: NAVSA Conference
  welcome_message: 'Welcome to Conference COVE Studio'
  welcome_blurb: 'COVE Studio is a web application that supports close reading and collaborative interpretation of online documents.'
  site_color: '#671900'
  home_banner: 'navsa_2020.png'
  brand: 'shared/navsa_conference_brand'
bavs-staging.covecollective.org:
  site_name: BAVS
  oauth_provider: BAVS
  welcome_message: 'Sign in via <a href="https://bavs.ac.uk/">BAVS</a>'
  welcome_blurb: 'Welcome the BAVS imprint of COVE, The Central Online Victorian Educator. COVE is a scholar-driven open-access platform that publishes peer-reviewed Victorian material. It is maintained and supported by NAVSA, BAVSA, AVSA and a number of independent institutions, and aims to make access to diverse scholarly editions and Victorian voices more widely available. Although all peer-reviewed material is open access, we charge a modest amount for use of our tools (for more information, see COVE Tools and Anthology Builder below). To facilitate its use throughout the COVID-19 pandemic, BAVS are offering some funds to support student access to develop specific projects. For more information on this, and for any other BAVS-specific issues regarding COVE use, please contact <a href="mailto:Joanna.taylor@manchester.ac.uk">Joanna Taylor</a>. If you are interested in getting involved with COVE, please contact General Editor <a href="mailto:felluga@purdue.edu">Dino Franco Felluga</a>.'
  site_color: '#279eb2'
  home_banner: 'bavs-banner.jpg'
  brand: 'shared/bavs_brand'
bavs.covecollective.org:
  site_name: BAVS
  oauth_provider: BAVS
  welcome_message: 'Sign in via <a href="https://bavs.ac.uk/">BAVS</a>'
  welcome_blurb: 'Welcome the BAVS imprint of COVE, The Central Online Victorian Educator. COVE is a scholar-driven open-access platform that publishes peer-reviewed Victorian material. It is maintained and supported by NAVSA, BAVSA, AVSA and a number of independent institutions, and aims to make access to diverse scholarly editions and Victorian voices more widely available. Although all peer-reviewed material is open access, we charge a modest amount for use of our tools (for more information, see COVE Tools and Anthology Builder below). To facilitate its use throughout the COVID-19 pandemic, BAVS are offering some funds to support student access to develop specific projects. For more information on this, and for any other BAVS-specific issues regarding COVE use, please contact <a href="mailto:Joanna.taylor@manchester.ac.uk">Joanna Taylor</a>. If you are interested in getting involved with COVE, please contact General Editor <a href="mailto:felluga@purdue.edu">Dino Franco Felluga</a>.'
  site_color: '#279eb2'
  home_banner: 'bavs-banner.jpg'
  brand: 'shared/bavs_brand'
purdue-staging.covecollective.org:
  site_name: Purdue
  welcome_message: 'Welcome to COVE Studio for Purdue'
  welcome_blurb: 'Welcome to COVE Studio for Purdue'
  site_color: '#CFB53B'
  home_banner: 'purdue_banner.jpg'
  brand: 'shared/purdue_brand'
  saml_provider: 'purdue.edu'
  saml_metadata: '/saml/purdue_staging_metadata.xml'
  saml_attributes:
    email: 'urn:oid:0.9.2342.19200300.100.1.3'
    firstname: 'urn:oid:2.5.4.42'
    lastname: 'urn:oid:2.5.4.4'
princeton-staging.covecollective.org:
  site_name: Princeton Staging
  welcome_message: 'Welcome to COVE Studio for Princeton'
  welcome_blurb: 'Welcome to COVE Studio for Princeton'
  site_color: '#e77500'
  home_banner: 'princeton_banner.jpg'
  brand: 'shared/princeton_brand'
  saml_provider: 'princeton.edu'
  saml_metadata: '/saml/princeton_staging_metadata.xml'
  saml_attributes:
      email: ‘urn:oid:1.3.6.1.4.1.5923.1.1.1.6’
      firstname: 'urn:oid:2.5.4.42'
      lastname: 'urn:oid:2.5.4.4'
princeton.covecollective.org:
  site_name: Princeton
  welcome_message: 'Welcome to COVE Studio for Princeton'
  welcome_blurb: 'Welcome to COVE Studio for Princeton'
  site_color: '#e77500'
  home_banner: 'princeton_banner.jpg'
  brand: 'shared/princeton_brand'
  saml_provider: 'princeton.edu'
  saml_metadata: '/saml/princeton_metadata.xml'
  saml_attributes:
      email: ‘urn:oid:1.3.6.1.4.1.5923.1.1.1.6’
      firstname: 'urn:oid:2.5.4.42'
      lastname: 'urn:oid:2.5.4.4'
nassr-staging.covecollective.org:
  site_name: NASSR Staging
  welcome_message: 'Welcome to COVE Studio for NASSR'
  welcome_blurb: 'Welcome to COVE Studio for NASSR'
  site_color: '#5f7457'
  home_banner: 'nassr_banner.jpg'
  brand: 'shared/nassr_brand'
nassr.covecollective.org:
  site_name: NASSR
  welcome_message: 'Welcome to COVE Studio for NASSR'
  welcome_blurb: 'Welcome to COVE Studio for NASSR'
  site_color: '#5f7457'
  home_banner: 'nassr_banner.jpg'
  brand: 'shared/nassr_brand'
